[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --connect-under-reset --chip STM32F042K6Tx"

# Enable flip-link linker for stack protection
rustflags = [
    "-C", "linker=flip-link",
]
