name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv6m-none-eabi
          components: clippy
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv6m-none-eabi
          components: rustfmt
      - name: Rustfmt
        run: cargo fmt --all -- --check
